version: '3.8'
name: 'nextjs-sample1'
services:
  sample1:
    container_name: nextjs-sample1
    hostname: sample1
    build: .
    image: nodejs:18.14.2-r0
    volumes:
    - ../:/root
    ports:
      - 3000:3000
    working_dir: /root
    tty: true
#    command: ["bash", "--login"]
